# Generated by Django 5.2.6 on 2025-09-20 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_dashboard_kpicard_savedquery_widget'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedquery',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='dashboard',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='ingestion.datasource'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='grid_columns',
            field=models.PositiveIntegerField(default=12, help_text='Columnas del grid (1-12)'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='is_auto_generated',
            field=models.BooleanField(default=False, help_text='Dashboard generado automáticamente'),
        ),
        migrations.AddField(
            model_name='kpicard',
            name='color',
            field=models.CharField(choices=[('primary', 'Azul'), ('success', 'Verde'), ('warning', 'Amarillo'), ('danger', 'Rojo'), ('info', 'Cyan')], default='primary', max_length=20),
        ),
        migrations.AddField(
            model_name='kpicard',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='Clase de icono (ej: fas fa-dollar-sign)', max_length=50),
        ),
        migrations.AddField(
            model_name='savedquery',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ingestion.datasource'),
        ),
        migrations.AddField(
            model_name='widget',
            name='color_scheme',
            field=models.CharField(choices=[('default', 'Por defecto'), ('blue', 'Azul'), ('green', 'Verde'), ('red', 'Rojo'), ('purple', 'Morado')], default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='widget',
            name='height',
            field=models.PositiveIntegerField(default=400, help_text='Altura en pixels'),
        ),
        migrations.AddField(
            model_name='widget',
            name='width',
            field=models.PositiveIntegerField(default=6, help_text='Ancho en columnas (1-12)'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='chart_type',
            field=models.CharField(choices=[('bar', 'Barras'), ('line', 'Líneas'), ('pie', 'Circular'), ('doughnut', 'Dona'), ('scatter', 'Dispersión'), ('radar', 'Radar'), ('area', 'Área')], default='bar', max_length=12),
        ),
        migrations.CreateModel(
            name='DataAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('numeric_columns', models.JSONField(default=list)),
                ('text_columns', models.JSONField(default=list)),
                ('date_columns', models.JSONField(default=list)),
                ('suggested_charts', models.JSONField(default=list)),
                ('analyzed_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='ingestion.datasource')),
            ],
        ),
    ]
